// Assemble the agent-written sections + screenshots into a single self-contained
// HTML document (screenshots embedded as base64 so the PDF needs no external
// files). No AI here — this just lays out what the agent produced.

import { readFile } from 'node:fs/promises'
import { isAbsolute, join } from 'node:path'
import { marked } from 'marked'
import type { ManualInput } from './types.js'

const md = (s: string) => marked.parse(s, { async: false }) as string
const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

async function dataUri(path: string, baseDir: string): Promise<string | null> {
  try {
    const abs = isAbsolute(path) ? path : join(baseDir, path)
    return `data:image/png;base64,${(await readFile(abs)).toString('base64')}`
  } catch { return null }
}

async function imgTag(screenshot: string, baseDir: string): Promise<string> {
  const uri = await dataUri(screenshot, baseDir)
  return uri ? `<img class="shot" src="${uri}" alt="screenshot" />` : ''
}

// Inline every relative <img src="…"> (e.g. close-ups dropped into a section's
// markdown) as a base64 data URI, so the PDF is fully self-contained.
async function inlineImages(html: string, baseDir: string): Promise<string> {
  const srcs = [...new Set([...html.matchAll(/src="([^"]+)"/g)].map(m => m[1]).filter(s => !/^(data:|https?:)/.test(s)))]
  let out = html
  for (const src of srcs) {
    const uri = await dataUri(src, baseDir)
    if (uri) out = out.split(`src="${src}"`).join(`src="${uri}"`)
  }
  return out
}

const CSS = `
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1c2128; line-height: 1.6; margin: 0; }
  .page { padding: 0 8mm; }
  h1 { font-size: 30px; margin: 0 0 6px; letter-spacing: -0.02em; }
  h2 { font-size: 21px; margin: 26px 0 8px; padding-top: 10px; border-top: 2px solid #eceff3; page-break-after: avoid; }
  h3 { font-size: 15px; margin: 16px 0 6px; color: #3b4351; text-transform: uppercase; letter-spacing: 0.04em; }
  p, li { font-size: 12.5px; }
  code { background: #f2f4f7; padding: 1px 5px; border-radius: 4px; font-size: 11.5px; }
  em { color: #5b6573; }
  .cover { height: 247mm; display: flex; flex-direction: column; justify-content: center; page-break-after: always; }
  .cover .badge { font-size: 12px; font-weight: 700; letter-spacing: 0.18em; text-transform: uppercase; color: #6b7280; }
  .cover h1 { font-size: 46px; margin: 8px 0; }
  .cover .sub { font-size: 15px; color: #5b6573; }
  .cover .meta { margin-top: auto; font-size: 11px; color: #8b949e; }
  .toc { page-break-after: always; }
  .toc li { margin: 4px 0; }
  .shot { width: 100%; border: 1px solid #e3e8ef; border-radius: 8px; margin: 10px 0 4px; page-break-inside: avoid; }
  .section { margin-bottom: 8px; }
  .section h2 { page-break-before: auto; }
  /* close-ups embedded in section markdown */
  p > img, li > img { display: block; max-width: 78%; margin: 8px auto 2px; border: 1px solid #e3e8ef; border-radius: 6px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); page-break-inside: avoid; }
  .tag { display: inline-block; font-size: 10px; color: #6b7280; border: 1px solid #e3e8ef; border-radius: 999px; padding: 1px 8px; margin-left: 6px; vertical-align: middle; }
  .credit { margin-top: 14px; font-size: 10px; color: #aab2bd; }
`

export async function buildHtml(manual: ManualInput, baseDir: string): Promise<string> {
  const now = new Date().toLocaleString()
  const toc = manual.sections.map((s, i) => `<li>${i + 1}. ${esc(s.title)}</li>`).join('')
  const body: string[] = []
  for (const [i, s] of manual.sections.entries()) {
    const lead = s.screenshot ? await imgTag(s.screenshot, baseDir) : ''
    body.push(`<div class="section"><span class="tag">${esc(s.title)} · §${i + 1}</span>${lead}${md(s.markdown)}</div>`)
  }
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>${CSS}</style></head><body>
  <div class="page">
    <div class="cover">
      <div class="badge">User Manual</div>
      <h1>${esc(manual.appName)}</h1>
      <div class="sub">${esc(manual.baseUrl)}</div>
      <div class="meta">Generated by manuscribe with Claude Code · ${esc(now)}</div>
    </div>

    <div class="toc">
      <h2>Contents</h2>
      <ol style="list-style:none;padding:0">${toc}</ol>
    </div>

    ${manual.overview ? md(manual.overview) : ''}
    ${body.join('\n')}
    ${manual.dataFlow ? md(manual.dataFlow) : ''}
    ${manual.glossary ? md(manual.glossary) : ''}

    <p class="credit">Generated automatically from the live application by manuscribe (ZeroAI), written by Claude Code. Review for accuracy before distribution.</p>
  </div>
  </body></html>`
  return inlineImages(html, baseDir)
}
