// Render the assembled HTML to a print-ready PDF using the same browser engine
// (Playwright/Chromium) we already use for crawling — no extra PDF dependency.

import { chromium } from 'playwright'

export async function htmlToPdf(html: string, outPath: string): Promise<void> {
  const browser = await chromium.launch({ headless: true })
  try {
    const page = await browser.newPage()
    await page.setContent(html, { waitUntil: 'load' })
    await page.pdf({
      path: outPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '14mm', bottom: '16mm', left: '0mm', right: '0mm' },
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate:
        '<div style="width:100%;font-size:8px;color:#aab2bd;padding:0 12mm;display:flex;justify-content:space-between;">' +
        '<span>Generated by manuscribe</span>' +
        '<span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span></div>',
    })
  } finally {
    await browser.close()
  }
}
